export const CLASS_DEFENSE_SESSION_STATUS = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  ENDED: 'ENDED',
} as const

export const CLASS_DEFENSE_PARTICIPANT_STATUS = {
  ALIVE: 'ALIVE',
  DOWN: 'DOWN',
} as const

export const CLASS_DEFENSE_MONSTER_STATUS = {
  WAITING: 'WAITING',
  WALKING: 'WALKING',
  COMBAT: 'COMBAT',
  KILLED: 'KILLED',
  REACHED: 'REACHED',
} as const

export const CLASS_DEFENSE_COMBAT_STATUS = {
  ACTIVE: 'ACTIVE',
  RESOLVED: 'RESOLVED',
  EXPIRED: 'EXPIRED',
  CANCELLED: 'CANCELLED',
} as const

export const CLASS_DEFENSE_EVENT_TYPE = {
  SESSION_STARTED: 'SESSION_STARTED',
  SESSION_ENDED: 'SESSION_ENDED',
  STUDENT_JOINED: 'STUDENT_JOINED',
  STUDENT_DOWN: 'STUDENT_DOWN',
  STUDENT_REVIVED: 'STUDENT_REVIVED',
  MONSTER_SPAWNED: 'MONSTER_SPAWNED',
  MONSTER_UPDATED: 'MONSTER_UPDATED',
  MONSTER_LOCKED: 'MONSTER_LOCKED',
  MONSTER_RELEASED: 'MONSTER_RELEASED',
  MONSTER_KILLED: 'MONSTER_KILLED',
  MONSTER_REACHED: 'MONSTER_REACHED',
  CLASS_HP_CHANGED: 'CLASS_HP_CHANGED',
  COMBAT_STARTED: 'COMBAT_STARTED',
  COMBAT_RESULT: 'COMBAT_RESULT',
} as const

export const CLASS_DEFENSE_TOKEN_USE = {
  ACCESS: 'CLASS_DEFENSE_ACCESS',
  WS_TICKET: 'CLASS_DEFENSE_WS_TICKET',
} as const
